# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/doublet_data/hitgraphs_med_000
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/triplet_data/hitgraphs_med_000

# Doublet trainer model
doublet_model_dir: /global/cscratch1/sd/danieltm/ExaTrkX/doublet_results/agnn07

# Graph building configuration
include_scores: True
