output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/triplet_results/checkpoints_high_000/agnn01

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/triplet_data/hitgraphs_high_000
    n_train: 32768
    n_valid: 4096
    real_weight: 3. #5.0   # 0.5 / 0.1
    batch_size: 4
    n_workers: 4

model:
    name: tripgnn
    input_dim: 7
    hidden_dim: 64
    n_graph_iters: 3
    layer_norm: true
    loss_func: binary_cross_entropy_with_logits

optimizer:
    name: Adam #SGD
    #momentum: 0.9
    learning_rate: 0.001
    lr_scaling: sqrt
    lr_warmup_epochs: 5
    lr_decay_schedule:
        - {start_epoch: 10, end_epoch: 20, factor: 0.5}
        - {start_epoch: 20, end_epoch: 40, factor: 0.1}
        - {start_epoch: 40, end_epoch: 50, factor: 0.05}
        - {start_epoch: 50, end_epoch: 64, factor: 0.01}

training:
    n_epochs: 64
